FROM ubuntu:20.04

#Datos del autor
LABEL author="Roberto Orazi" mail="robervgg@gmail.com"

#Variables de entorno
ENV container docker

# Instalamos las dependencias
RUN apt-get update && apt-get install -y \
    curl \
    imagemagick \
    zip

# Metemos los scripts al contenedor
COPY generar.sh /generar.sh
COPY descomprimir.sh /descomprimir.sh
COPY procesar.sh /procesar.sh
COPY comprimir.sh /comprimir.sh
COPY menu.sh /menu.sh


# Le damos permiso de ejecucion a los scripts
RUN chmod +x /generar.sh
RUN chmod +x /descomprimir.sh
RUN chmod +x /procesar.sh
RUN chmod +x /comprimir.sh
RUN chmod +x /menu.sh

# Configuramos el punto de entrada, en este caso el menush que es el que ejecuta todos los scripts
ENTRYPOINT [ "bash", "/app/bash/menu.sh"]