FROM ubuntu:20.04

#Datos del autor
LABEL author="Roberto Orazi" mail="robervgg@gmail.com"

#Variables de entorno
ENV container docker

# Instalamos las dependencias
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y imagemagick
RUN apt-get install -y zip
#RUN apt-get update && apt-get install -y \
#    curl \
#    imagemagick \
#    zip

# Metemos los scripts al contenedor
COPY generar.sh ../bash/script/
COPY descomprimir.sh ../bash/script/
COPY procesar.sh ../bash/script/
COPY comprimir.sh ../bash/script/
COPY menu.sh ../bash/


# Le damos permiso de ejecucion a los scripts
RUN chmod +x /bash/script/generar.sh
RUN chmod +x /bash/script/descomprimir.sh
RUN chmod +x /bash/script/procesar.sh
RUN chmod +x /bash/script/comprimir.sh
RUN chmod +x /bash/menu.sh

# Configuramos el punto de entrada, en este caso el menush que es el que ejecuta todos los scripts
ENTRYPOINT [ "bash", "/bash/menu.sh"]